version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "strava-messenger"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fsj0vl61qbnk"
s3_prefix = "strava-messenger"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
